version: "3.3"
services:
  website:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - ~/.config:/.config
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /.config/gcloud/application_default_credentials.json
